allowBuilds:
  lefthook: true
ignoredBuiltDependencies:
  - esbuild
minimumReleaseAgeExclude:
  - vite@6.3.6 || 6.4.1 || 6.4.2
  - esbuild@0.28.1
  - postcss@8.5.18
onlyBuiltDependencies:
  - lefthook
overrides:
  postcss@<=8.5.17: ^8.5.18
