name: Publish
on:
  push:
    tags:
      - "*"

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Cache devenv
        uses: cachix/cachix-action@v16
        with:
          name: devenv
          skipPush: true

      - name: Install devenv
        run: nix profile add nixpkgs#devenv

      - name: Install dependencies
        run: devenv shell -- pnpm ci

      - name: Quality checks
        run: devenv shell -- pnpm qa

      - name: Publish
        run: |
          TAG=$(node -e "const v = require('./package.json').version; process.stdout.write(v.includes('-') ? 'beta' : 'latest')")
          devenv shell -- npm publish --provenance --no-git-checks --tag $TAG
