name: Publish
on:
  push:
    tags:
      - "*"

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mise install
        run: |
          curl https://mise.run | sh
          mise install

      - name: Install dependencies
        run: mise x -- pnpm install --frozen-lockfile

      - name: Quality checks
        run: mise x -- pnpm test && mise x -- pnpm lint && mise x -- pnpm typecheck

      - name: Build
        run: mise x -- pnpm build

      - name: Build and publish
        run: mise x -- pnpm publish --provenance
