name: Publish
on:
  push:
    tags:
      - "*"

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Mise install
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: mise x -- pnpm install --frozen-lockfile

      - name: Quality checks
        run: mise x -- pnpm qa

      - name: Publish
        run: |
          TAG=$(node -e "const v = require('./package.json').version; process.stdout.write(v.includes('-') ? 'beta' : 'latest')")
          mise x -- pnpm publish --provenance --tag $TAG
